apiVersion: v1

kind: ConfigMap

metadata:
  name: backend-config

  namespace: ai-fullstack

data:

  DATABASE_HOST: postgres

  DATABASE_PORT: "5432"

  DATABASE_NAME: ai_fullstack_db

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  JWT_ALGORITHM: HS256

  ACCESS_TOKEN_EXPIRE_MINUTES: "30"